
# platform :ios, '9.0'

target 'FirebasePractice1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebasePractice1
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end
